artifacts:
  ARTIFACTS_DIR: artifacts
  BASE_MODEL_FILE_PATH: artifacts/models/base_model.h5
  UNTRAINED_MODEL_FILE_PATH: artifacts/models/untrained_full_model.h5
  TRAINED_MODEL_FILE_PATH: artifacts/models/trained_model.h5
  BLESSED_MODEL_FILE_PATH: artifacts/models/blessed_model.h5
  CHECKPOINTS_DIR: artifacts/checkpoints
  CHECKPOINT_FILE_PATH: artifacts/checkpoints/.mdl_wts.hdf5
  MODEL_EVAL_DIR: artifacts/model_evaluation
  MODEL_EVALUATION_PLOT : artifacts/model_evaluation/eval_metrics.jpg
  CONFUSION_MATRIX_PLOT_FILE_PATH: artifacts/model_evaluation/confusion_metrics.jpg

local_data:
  DATA_DIR : dataset

logs:
  LOGS_DIR : logs
  RUNNING_LOGS_FILE_PATH: logs/running_logs.log
  TENSORBOARD_ROOT_LOGS_DIR: logs/tensorboard_logs_dir

mlflow:
  EXPERIMENT_NAME: automlExp
  RUN_ID_PREFIX: local #change to online for deploying the code as pipeline
  MODEL_NAME : Covid-19
  LOGGED_MODEL_DIR: logged_model

gcs_config:
  BUCKET_NAME: mlops-378116
  DATA_DIR : mlops-378116/covid-19
  ARTIFACTS : mlops-378116/covid-19/artifacts

  BASE_MODEL_FILE_PATH: covid-19/artifacts/models/base_model.h5
  UNTRAINED_MODEL_FILE_PATH: covid-19/artifacts/models/untrained_full_model.h5
  TRAINED_MODEL_FILE_PATH: covid-19/artifacts/models/trained_model.h5
  BLESSED_MODEL_FILE_PATH: covid-19/artifacts/models/blessed_model.h5

  CHECKPOINTS_DIR: mlops-378116/covid-19/artifacts/checkpoints
  MODEL_EVAL_DIR: mlops-378116/covid-19/artifacts/model_evaluation

  LOGS_DIR : mlops-378116/covid-19/logs
  TENSORBOARD_ROOT_LOGS_DIR : mlops-378116/covid-19/logs/tensorboard_logs_dir
  LOGS_FILE_PATH : covid-19/logs/running_logs.log

mlflow:
  EXPERIMENT_NAME: CovidBaseExp
  RUN_ID_PREFIX: online #change to online for deploying the code as pipeline
  MODEL_NAME : Covid-19 Model

model_serving:
  PRODUCTION_MODEL_PATH: src/production_model/model.h5
  INPUT_IMG_FILE_PATH: src/images/input.jpg
  OUTPUT_IMG_FILE_PATH: src/images/out.jpg
  CLASS_INDICES : {'covid': 0, 'normal': 1, 'virus': 2}
  APP_HOST : 0.0.0.0
  APP_PORT : 8080
  API_TITLE: Covid-19 Image Classification Service
  API_DESCRIPTION: The REST API service accepts base64 encoded image and returns the predicted class, confidence scores and a base64 encoded image with the class activation map.
  API_VERSION: 0.0.3
